### ISSUE TITLE
Ensure users can inherit from relations for alternative adapters

### ISSUE THREAD

**Issue by timriley** [hanami/db#3]
As a starting point, we've defaulted to the `:sql` adapter for `Hanami::DB::Relation`, but users should be able to provide alternatives.

I'd prefer we offer a way that is _not_ subclassing from `Hanami::DB::Relation[:adapter_name]`, since that is a syntax that will feel foreign and uncomfortable to many. We have no precedents for such a syntax being used on class inheritance within Hanami, and I'd prefer not to introduce it, if we can avoid it.

However, I'm not sure if it's avoidable in the first place, if you look at the implementation of `ROM::Relation.[]`:

```ruby
def [](adapter)
  ROM.adapters.fetch(adapter).const_get(:Relation)
rescue KeyError
  raise AdapterNotPresentError.new(adapter, :relation)
end
```

We really need to do this at the time of inheritance, since there could be very different superclasses returned from that method.

I wonder if `< Hanami::DB::Relation.adapter(adapter_name)` might at least make things clearer? We could support this an alias.

**Comment by alassek** [comment]
It's not entirely unheard of, consider the case of [ActiveRecord Migrations](https://guides.rubyonrails.org/active_record_migrations.html) in Rails

```ruby
class CreateProducts < ActiveRecord::Migration[7.1]
  def change
    create_table :products do |t|
      t.string :name
      t.text :description

      t.timestamps
    end
  end
end
```

I'm concerned that anything more magical than this could lead to unpredictable behavior. You should be able to write the syntax of the base class in a REPL and see the concrete class it returns.

**Comment by alassek** [comment]
> I wonder if `< Hanami::DB::Relation.adapter(adapter_name)` might at least make things clearer?

`adapter` is already a class attribute of Relation that returns the adapter name as a Symbol. This feels like load-bearing API that we don't want to change.

What do you think of `< Hanami::DB::Relation.for(adapter_name)`?

**Comment by timriley** [comment]
Thanks for looking into this and putting together #10 to demonstrate it, @alassek :)

With `.adapter` not available, the example of Rails' `.[]` inheritance usage, and with our  Hanami 2.2 goal of "putting ROM on a platter" for the user, I think we're best served by sticking with ROM's native syntax here, and not adding any aliases.

What also goes into my thinking here is that I think the `.for` in `Hanami::Relation.for` is more likely to be confused by setting the relation's _schema name_ instead of its adapter. For example: “What is this relation _for_?” “It's the _articles_ relation.”

How does this decision feel to you?

--

Aside from the aliasing/naming discussion, there is still a task to be done here: we need to add a test to hanami that demonstrates an alternative adapter being used. So let's just make that the focus of this issue for from here on.

**Comment by alassek** [comment]
> What also goes into my thinking here is that I think the `.for` in `Hanami::Relation.for` is more likely to be confused by setting the relation's schema name instead of its adapter. For example: “What is this relation *for*?” “It's the *articles* relation.”

Good point. I agree that this is very likely to add confusion. We'll have to rely on documentation to clarify what adapter selection is for.
